version: '3'
services:
  redis:
    image: redis:latest
    container_name: my-redis
    networks:
      - mynetwork

  weatherapp:
    image: weatherapp:v1  # Replace with the actual image name
    container_name: weatherwebsite
    ports:
      - "8000:8000"
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
